# Generated by Django 4.1.3 on 2022-11-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('itemsinStock', models.CharField(max_length=200)),
                ('colorsAvailable', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('bikeCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
    ]
