# Generated by Django 4.1.3 on 2022-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bikes_purchased_purchasedbikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='price',
            field=models.IntegerField(),
        ),
    ]
