# Generated by Django 4.1.3 on 2022-11-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_alter_bikes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bikes', models.ManyToManyField(to='base.bikes')),
            ],
            options={
                'ordering': ['cart_id', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='purchasedBikes',
        ),
    ]
