# Generated by Django 4.1.3 on 2022-11-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cart_delete_purchasedbikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bikes',
        ),
        migrations.AddField(
            model_name='cart',
            name='bikes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bikes'),
        ),
    ]
