# Generated by Django 4.1.3 on 2022-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_cart_bikes_cart_bikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bikes',
        ),
        migrations.AddField(
            model_name='cart',
            name='bikes',
            field=models.ManyToManyField(to='base.bikes'),
        ),
    ]
