# Generated by Django 4.1.3 on 2022-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_cart_bikes_cart_bikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='warranty',
            field=models.DateField(),
        ),
    ]
