# Generated by Django 4.1.3 on 2022-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_bikes_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='warranty',
            field=models.DateTimeField(),
        ),
    ]
