# Generated by Django 4.1.3 on 2022-11-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_bikes_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='warranty',
            field=models.DateField(),
        ),
    ]
